ERROR:root:no_return
  raised Exception: DO NOT PASS GO DO NOT COLLECT $200.
    called with "args = (), kwargs = {}"
    at "2022-01-02 22:40:33.287978-05:00"
Traceback (most recent call last):
  File "/home/ryan/exception-logging-decorator/exception_logger/main.py", line 65, in wrapper
    output = function(*args, **kwargs)
  File "/home/ryan/exception-logging-decorator/test.py", line 11, in no_return
    raise Exception("DO NOT PASS GO DO NOT COLLECT $200.")
Exception: DO NOT PASS GO DO NOT COLLECT $200.
