ERROR:root:no_return
  raised Exception: DO NOT PASS GO DO NOT COLLECT $200.
    called with args = (), kwargs = {}
    at 2022-03-08 14:07:54.325358-05:00
Traceback (most recent call last):
  File "/home/ryan/exception-logging/src/exlog/exceptlog.py", line 58, in wrapper
    output = function(*args, **kwargs)
  File "/home/ryan/exception-logging/./tests/test_logger.py", line 20, in no_return
    raise Exception("DO NOT PASS GO DO NOT COLLECT $200.")
Exception: DO NOT PASS GO DO NOT COLLECT $200.
